name: Monitor Health Factor zero

# Programar el flujo de trabajo para que se ejecute cada 5 minutos
on:
  schedule:
    - cron: '*/500 * * * *'  # Ejecuta cada 5 minutos
  push:
    branches:
      - main  # Ejecuta también cuando empujes cambios a la rama principal (opcional)

jobs:
  run-script:
    runs-on: ubuntu-latest  # Usaremos Ubuntu para ejecutar el script

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Obtener el código del repositori

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Configurar Node.js
      with:
        node-version: '16'  # Asegúrate de que la versión de Node.js sea compatible con tu 

    - name: Install dependencies
      run: npm install  # Instalar las dependencias de Node.js (si tienes un package.json)

    - name: Run the script
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}  # Accediendo al Secret de la PK
      run: |
        node index.js
